version: "2"
services:
  db:
    container_name: pg
    image: "postgres:9.6"
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  redis:
    image: "docker.io/bitnami/redis:6.0-debian-10"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
volumes:
  redis_data:
    driver: local
